### ISSUE TITLE
Gloves when Construct's Armory is present

### ISSUE THREAD

**Issue by levilips123** [Shnupbups/TinkersAether#9] opened 2018-08-16 19:57 UTC
are they coming ? the gloves could add some more armour and some more buffs or something . or as modifiers for them instead of the gauntlets from the base construct armory it would have its own modifiers and have durability as well . liek instead of the speed gauntlet you put redstone on it instead of the powerful gauntlet you put quartz on it and instead of the telekinetick modifier you put valkyrie metal and some golden amber . since it is an armor piece I dont see why it wouldnt add protection . all the other modifiers from construct armory can do the same thing like diamond or wither bone or emerald or resistance . heck you could even add lapis and gravitite to them to make your tool more lucky or something . since just lapis would be too easy . like a gravitite block and 4 lapis blocks . those are just some ideas I came up with since I am very excited about some tinkers gloves because I dont have any reason to put a glove in my slot because it is weird looking it just passes through the chestplate . I want to see your opinion on this subject .

**Comment by Shnupbups** [comment] 2018-08-17 08:05
Yes, Construct's Armory support is coming, and will include the ability to make gloves.

**Comment by Shnupbups** [comment] 2018-08-17 08:07
Duplicate of [Issue 4](4)

**Closed as completed by Shnupbups** 2018-08-17 08:07 UTC
Labels: duplicate, enhancement

**Comment by levilips123** [comment] 2018-08-17 17:16
but are you gonna take some of these ideas into consideration ?

**Comment by Shnupbups** [comment] 2018-08-18 02:00
To be truthful, I'm not entirely sure I understand all of your ideas.

But my plan for Gloves is as follows:
- You will be able to make them out of any material
- They will have the same traits, for the most part, as other armour pieces (with some unique ones)
- They will increase your attack damage when punching with empty fists
- This attack bonus can be furthered with quartz, adding spiked knuckles to the gauntlet
- Adding redstone will increase your break speed when breaking with empty fists
- Adding lapis will add luck when breaking with empty fists (if a block that can be harvested with fists supports fortune...)
- All of these effects **only work if you aren't holding anything!** (or maybe if you're holding anything that isn't a tool. I haven't decided yet. Maybe a config option?)
- They will take durability damage like armour, unlike their Aether counterparts

Other general armour-based plans:
- Set bonuses from Aether *will work*, but you'll still need a full set including gloves
- There will be armour traits for each material
- Neptune and Phoenix will probably be modifiers, rather than materials

**Comment by levilips123** [comment] 2018-08-20 15:42
I want them to at least give more protection since it makes sense because they're made to be wore by the player as an armor piece . also I'd like to point out that the construct armory chestplate has gloves . when your mod is present you should remove that. I am a little concerned about the gauntlet modifiers for the chestplate from construct armory . you could keep them in the game to be for the chestplate by removing their texture and let them be an invisible modifier
